// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzor1vG3sS5R6rUQsPObyxXQgPZBw7B1E',
    appId: '1:404584685579:web:85936c82f214e391a8a70e',
    messagingSenderId: '404584685579',
    projectId: 'createnavbar',
    authDomain: 'createnavbar.firebaseapp.com',
    storageBucket: 'createnavbar.appspot.com',
    measurementId: 'G-2LXDQW09WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNHRSez5AAMMjn1Kwd60BAjU3oPFMAxM',
    appId: '1:404584685579:android:7d85d8caefeb1c44a8a70e',
    messagingSenderId: '404584685579',
    projectId: 'createnavbar',
    storageBucket: 'createnavbar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5dc6yvseqbpNZeC7PFYi_BMwjRORlHLU',
    appId: '1:404584685579:ios:2d0a43600fd4a283a8a70e',
    messagingSenderId: '404584685579',
    projectId: 'createnavbar',
    storageBucket: 'createnavbar.appspot.com',
    iosBundleId: 'com.example.createNavBar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5dc6yvseqbpNZeC7PFYi_BMwjRORlHLU',
    appId: '1:404584685579:ios:114747cbd06a6262a8a70e',
    messagingSenderId: '404584685579',
    projectId: 'createnavbar',
    storageBucket: 'createnavbar.appspot.com',
    iosBundleId: 'com.example.createNavBar.RunnerTests',
  );
}
